export const TYPE_DICT = {
  LOWER_CASE: 'LOWER_CASE',
  CAPITALIZED_CASE: 'CAPITALIZED_CASE',
  UPPER_CASE: 'UPPER_CASE',
};

export const DICT = [
  'don shopee',
  'gui don shopee',
  'chuyen don shopee',
  'tra don shopee',
  'no don shopee',
  'guiwr ddown shopee',
  'chuyeenr ddown shopee',
  'trar ddown shopee',
  'nowj ddown shopee',
  'guir ddon shopee',
  'chuyenr ddon shopee',
  'trar ddon shopee',
  'noj ddon shopee',
  'don hang shopee',
  'ddown hangf shopee',
  'ddon hangf shopee',
  'mua hang shopee',
  'mua hangf shopee',
  'hoan don shopee',
  'hoanf ddown shopee',
  'hoanf ddon shopee',
  'ship don shopee',
  'ship ddown shopee',
  'ship ddon shopee',
  'gui don lazada',
  'chuyen don lazada',
  'tra don lazada',
  'no don lazada',
  'guiwr ddown lazada',
  'chuyeenr ddown lazada',
  'trar ddown lazada',
  'nowj ddown lazada',
  'guir ddon lazada',
  'chuyenr ddon lazada',
  'trar ddon lazada',
  'noj ddon lazada',
  'don hang lazada',
  'ddown hangf lazada',
  'ddon hangf lazada',
  'mua hang lazada',
  'mua hangf lazada',
  'hoan don lazada',
  'hoanf ddown lazada',
  'hoanf ddon lazada',
  'ship don lazada',
  'ship ddown lazada',
  'ship ddon lazada',
  'gui don tiki',
  'chuyen don tiki',
  'tra don tiki',
  'no don tiki',
  'guiwr ddown tiki',
  'chuyeenr ddown tiki',
  'trar ddown tiki',
  'nowj ddown tiki',
  'guir ddon tiki',
  'chuyenr ddon tiki',
  'trar ddon tiki',
  'noj ddon tiki',
  'don hang tiki',
  'ddown hangf tiki',
  'ddon hangf tiki',
  'mua hang tiki',
  'mua hangf tiki',
  'hoan don tiki',
  'hoanf ddown tiki',
  'hoanf ddon tiki',
  'ship don tiki',
  'ship ddown tiki',
  'ship ddon tiki',
  'gui don foody',
  'chuyen don foody',
  'tra don foody',
  'no don foody',
  'guiwr ddown foody',
  'chuyeenr ddown foody',
  'trar ddown foody',
  'nowj ddown foody',
  'guir ddon foody',
  'chuyenr ddon foody',
  'trar ddon foody',
  'noj ddon foody',
  'don hang foody',
  'ddown hangf foody',
  'ddon hangf foody',
  'mua hang foody',
  'mua hangf foody',
  'hoan don foody',
  'hoanf ddown foody',
  'hoanf ddon foody',
  'ship don foody',
  'ship ddown foody',
  'ship ddon foody',
  'gui don winmart',
  'chuyen don winmart',
  'tra don winmart',
  'no don winmart',
  'guiwr ddown winmart',
  'chuyeenr ddown winmart',
  'trar ddown winmart',
  'nowj ddown winmart',
  'guir ddon winmart',
  'chuyenr ddon winmart',
  'trar ddon winmart',
  'noj ddon winmart',
  'don hang winmart',
  'ddown hangf winmart',
  'ddon hangf winmart',
  'mua hang winmart',
  'mua hangf winmart',
  'hoan don winmart',
  'hoanf ddown winmart',
  'hoanf ddon winmart',
  'ship don winmart',
  'ship ddown winmart',
  'ship ddon winmart',
  'gui don grab',
  'chuyen don grab',
  'tra don grab',
  'no don grab',
  'guiwr ddown grab',
  'chuyeenr ddown grab',
  'trar ddown grab',
  'nowj ddown grab',
  'guir ddon grab',
  'chuyenr ddon grab',
  'trar ddon grab',
  'noj ddon grab',
  'don hang grab',
  'ddown hangf grab',
  'ddon hangf grab',
  'mua hang grab',
  'mua hangf grab',
  'hoan don grab',
  'hoanf ddown grab',
  'hoanf ddon grab',
  'ship don grab',
  'ship ddown grab',
  'ship ddon grab',
  'gui don coopmart',
  'chuyen don coopmart',
  'tra don coopmart',
  'no don coopmart',
  'guiwr ddown coopmart',
  'chuyeenr ddown coopmart',
  'trar ddown coopmart',
  'nowj ddown coopmart',
  'guir ddon coopmart',
  'chuyenr ddon coopmart',
  'trar ddon coopmart',
  'noj ddon coopmart',
  'don hang coopmart',
  'ddown hangf coopmart',
  'ddon hangf coopmart',
  'mua hang coopmart',
  'mua hangf coopmart',
  'hoan don coopmart',
  'hoanf ddown coopmart',
  'hoanf ddon coopmart',
  'ship don coopmart',
  'ship ddown coopmart',
  'ship ddon coopmart',
  'gui don megamart',
  'chuyen don megamart',
  'tra don megamart',
  'no don megamart',
  'guiwr ddown megamart',
  'chuyeenr ddown megamart',
  'trar ddown megamart',
  'nowj ddown megamart',
  'guir ddon megamart',
  'chuyenr ddon megamart',
  'trar ddon megamart',
  'noj ddon megamart',
  'don hang megamart',
  'ddown hangf megamart',
  'ddon hangf megamart',
  'mua hang megamart',
  'mua hangf megamart',
  'hoan don megamart',
  'hoanf ddown megamart',
  'hoanf ddon megamart',
  'ship don megamart',
  'ship ddown megamart',
  'ship ddon megamart',
  'gui don do an',
  'chuyen don do an',
  'tra don do an',
  'no don do an',
  'guiwr ddown do an',
  'chuyeenr ddown do an',
  'trar ddown do an',
  'nowj ddown do an',
  'guir ddon do an',
  'chuyenr ddon do an',
  'trar ddon do an',
  'noj ddon do an',
  'don hang do an',
  'ddown hangf do an',
  'ddon hangf do an',
  'mua hang do an',
  'mua hangf do an',
  'hoan don do an',
  'hoanf ddown do an',
  'hoanf ddon do an',
  'ship don do an',
  'ship ddown do an',
  'ship ddon do an',
  'gui don quan',
  'chuyen don quan',
  'tra don quan',
  'no don quan',
  'guiwr ddown quan',
  'chuyeenr ddown quan',
  'trar ddown quan',
  'nowj ddown quan',
  'guir ddon quan',
  'chuyenr ddon quan',
  'trar ddon quan',
  'noj ddon quan',
  'don hang quan',
  'ddown hangf quan',
  'ddon hangf quan',
  'mua hang quan',
  'mua hangf quan',
  'hoan don quan',
  'hoanf ddown quan',
  'hoanf ddon quan',
  'ship don quan',
  'ship ddown quan',
  'ship ddon quan',
  'gui don ao',
  'chuyen don ao',
  'tra don ao',
  'no don ao',
  'guiwr ddown ao',
  'chuyeenr ddown ao',
  'trar ddown ao',
  'nowj ddown ao',
  'guir ddon ao',
  'chuyenr ddon ao',
  'trar ddon ao',
  'noj ddon ao',
  'don hang ao',
  'ddown hangf ao',
  'ddon hangf ao',
  'mua hang ao',
  'mua hangf ao',
  'hoan don ao',
  'hoanf ddown ao',
  'hoanf ddon ao',
  'ship don ao',
  'ship ddown ao',
  'ship ddon ao',
];

export const TEXT = [
  'ma',
  'Ma',
  'MA',
  'max',
  'Max',
  'MAX',
  'Cod',
  'Code',
  'code',
  'cod',
  'CODE',
  'COD',
  'id',
  'Id',
  'ID',
  'so',
  'So',
  'SO',
];
