export enum CREATE_POST_TYPE {
  ASSET_ID_IS_INVALID = 'ASSET_ID_IS_INVALID',
  POST_TYPE_IS_INVALID = 'POST_TYPE_IS_INVALID',
  FIAT_TYPE_IS_INVALID = 'FIAT_TYPE_IS_INVALID',
  USER_TO_MERCHANT_TIME_IS_EMPTY = 'USER_TO_MERCHANT_TIME_IS_EMPTY',
  USER_TO_MERCHANT_TIME_IS_INVALID = 'USER_TO_MERCHANT_TIME_IS_INVALID',
  FIXED_PRICE_BEFORE_FEE_IS_EMPTY = 'FIXED_PRICE_BEFORE_FEE_IS_EMPTY',
  FIXED_PRICE_BEFORE_FEE_IS_INVALID = 'FIXED_PRICE_BEFORE_FEE_IS_INVALID',
  PAYMENT_METHOD_IS_INVALID = 'PAYMENT_METHOD_IS_INVALID',
  LOWER_FIAT_LIMIT_IS_INVALID = 'LOWER_FIAT_LIMIT_IS_INVALID',
  UPPER_FIAT_LIMIT_IS_EMPTY = 'UPPER_FIAT_LIMIT_IS_EMPTY',
  UPPER_FIAT_LIMIT_IS_INVALID = 'UPPER_FIAT_LIMIT_IS_INVALID',
  UPPER_FIAT_LIMIT_IS_SMALLER_THAN_LOWER_ORDER_LIMIT = 'UPPER_FIAT_LIMIT_IS_SMALLER_THAN_LOWER_ORDER_LIMIT',
  CRYPTO_AMOUNT_IS_EMPTY = 'CRYPTO_AMOUNT_IS_EMPTY',
  CRYPTO_AMOUNT_IS_SMALLER_THAN_UPPER_ORDER_LIMIT = 'CRYPTO_AMOUNT_IS_SMALLER_THAN_UPPER_ORDER_LIMIT',
  MERCHANT_NOTE_IS_MAX_LENGTH = 'MERCHANT_NOTE_IS_MAX_LENGTH',
  POST_ID_IS_INVALID = 'POST_ID_IS_INVALID',
}

export enum SEARCH_POST_TYPE {
  ASSET_IS_INVALID = 'ASSET_IS_INVALID',
  FIAT_IS_INVALID = 'FIAT_IS_INVALID',
  PAGE_IS_INVALID = 'PAGE_IS_INVALID',
  ROWS_IS_INVALID = 'ROWS_IS_INVALID',
  TYPE_IS_INVALID = 'TYPE_IS_INVALID',
  LIMIT_IS_INVALID = 'LIMIT_IS_INVALID',
}

export enum CREATE_ORDER_TYPE {
  AMOUNT_IS_INVALID = 'AMOUNT_IS_INVALID',
  POST_ID_IS_INVALID = 'POST_ID_IS_INVALID',
  PRICE_IS_INVALID = 'PRICE_IS_INVALID',
}

export enum ORDER_LIST_TYPE {
  PAGE_IS_INVALID = 'PAGE_IS_INVALID',
  ROWS_IS_INVALID = 'ROWS_IS_INVALID',
  LIMIT_IS_INVALID = 'LIMIT_IS_INVALID',
  USER_ID_IS_INVALID = 'USER_ID_IS_INVALID',
  STATUS_IS_INVALID = 'STATUS_IS_INVALID',
  TYPE_IS_INVALID = 'TYPE_IS_INVALID',
}

export enum ORDER_CRYPTO_TRANSACTION {
  ORDER_ID_IS_INVALID = 'ORDER_ID_IS_INVALID',
  HASH_IS_INVALID = 'HASH_IS_INVALID',
}

export enum ORDER_SELL_CREATE_TYPE {
  PAYMENT_METHOD_ID_IS_INVALID = 'PAYMENT_METHOD_ID_IS_INVALID',
}

export enum ORDER_TYPE {
  ORDER_ID_IS_INVALID = 'ORDER_ID_IS_INVALID',
}

export enum LIST_PARAM_TYPE {
  PAGE_IS_INVALID = 'PAGE_IS_INVALID',
  LIMIT_IS_INVALID = 'LIMIT_IS_INVALID',
  DATE_RANGE_IS_INVALID = 'DATE_RANGE_IS_INVALID',
  DATE_IS_INVALID = 'DATE_IS_INVALID',
}

export enum PAYMENT_METHOD_CREATE_TYPE {
  BANK_NUMBER_IS_EMPTY = 'BANK_NUMBER_IS_EMPTY',
  BANK_NAME_IS_EMPTY = 'BANK_NAME_IS_EMPTY',
  BANK_HOLDER_IS_EMPTY = 'BANK_HOLDER_IS_EMPTY',
  PAYMENT_METHOD_IS_EMPTY = 'PAYMENT_METHOD_IS_EMPTY',
  BANK_NUMBER_IS_INVALID = 'BANK_NUMBER_IS_INVALID',
  BANK_NAME_IS_INVALID = 'BANK_NAME_IS_INVALID',
  BANK_HOLDER_IS_INVALID = 'BANK_HOLDER_IS_INVALID',
  BANK_REMARK_IS_INVALID = 'BANK_REMARK_IS_INVALID',
  PAYMENT_METHOD_IS_INVALID = 'PAYMENT_METHOD_IS_INVALID',
}

export enum APPEAL_TYPE {
  APPEAL_ID_IS_INVALID = 'APPEAL_ID_IS_INVALID',
  DECISION_RESULT_IS_INVALID = 'DECISION_RESULT_IS_INVALID',
}

export enum CREATE_SUBSCRIPTION_NOTIFICATION_TYPE {
  PLAYER_ID_IS_INVALID = 'PLAYER_ID_IS_INVALID',
}
export enum CREATE_SUBSCRIPTION_DEVICE_TYPE {
  DEVICE_ID_IS_INVALID = 'DEVICE_ID_IS_INVALID',
}

export enum UPDATE_NOTIFICATION_STATUS_TYPE {
  NOTIFICATION_STATUS_IS_INVALID = 'NOTIFICATION_STATUS_IS_INVALID',
}

export enum NOTIFICATION_LIST_TYPE {
  PAGE_IS_INVALID = 'PAGE_IS_INVALID',
  ROWS_IS_INVALID = 'ROWS_IS_INVALID',
  LIMIT_IS_INVALID = 'LIMIT_IS_INVALID',
  USER_ID_IS_INVALID = 'USER_ID_IS_INVALID',
  STATUS_IS_INVALID = 'STATUS_IS_INVALID',
  TYPE_IS_INVALID = 'TYPE_IS_INVALID',
}

export enum SETTING_MASTER_DATA_TYPE {
  MAX_ORDER_LIMIT_IS_SMALLER_THAN_MIN_ORDER_LIMIT = 'MAX_ORDER_LIMIT_IS_SMALLER_THAN_MIN_ORDER_LIMIT',
  MAX_POST_LIMIT_IS_SMALLER_THAN_MIN_POST_LIMIT = 'MAX_POST_LIMIT_IS_SMALLER_THAN_MIN_POST_LIMIT',
}

export enum EXPORT_REPORT_TYPE {
  REPORT_TYPE_INVALID = 'REPORT_TYPE_INVALID',
}
