import {MigrationInterface, QueryRunner} from "typeorm";

export class updateIdToUuidInAllTable1681464171635 implements MigrationInterface {
    name = 'updateIdToUuidInAllTable1681464171635'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_771ab23b45783e766836b2b44af\``);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP FOREIGN KEY \`FK_3dd742723f71ed49d0d4d7220bf\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_055606f75e7ed988a209b0cc22c\``);
        await queryRunner.query(`ALTER TABLE \`assets\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`assets\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`assets\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`assets\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` DROP FOREIGN KEY \`FK_1b1d3bc7dee89240f32a52ac1f1\``);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` CHANGE \`id\` \`id\` bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` DROP COLUMN \`order_id\``);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` ADD \`order_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP FOREIGN KEY \`FK_b88299cbbc4574c73b50c5d27f0\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2465b00898e757903f012d835cd\``);
        await queryRunner.query(`ALTER TABLE \`fiats\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`fiats\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`fiats\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`fiats\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` DROP FOREIGN KEY \`FK_3f2c5059700f1b5aac63578f1a8\``);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` DROP COLUMN \`payment_method_id\``);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` ADD \`payment_method_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP FOREIGN KEY \`FK_ffe1b182ad69c344e48536ffd5c\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_7819f136440d4ae83b20f0267a9\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD \`user_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_4431880582fab347b6290ee72b2\``);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP FOREIGN KEY \`FK_717ca4859d98ff25cb6b2a1e849\``);
        await queryRunner.query(`ALTER TABLE \`posts\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP COLUMN \`merchant_id\``);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD \`merchant_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP COLUMN \`asset_id\``);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD \`asset_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP COLUMN \`fiat_id\``);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD \`fiat_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP COLUMN \`payment_method_id\``);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD \`payment_method_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2474866c8f8e9196ff227a7cbbd\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_316f906335ce15e2848af3dd53a\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_f0b696b5d7c28733b2917bfb251\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_10d3b9250270115115b3d899d1f\``);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`id\` \`id\` bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`user_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`merchant_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`merchant_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`supporter_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`supporter_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`asset_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`asset_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`fiat_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`fiat_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`post_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`post_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`DROP INDEX \`REL_f0b696b5d7c28733b2917bfb25\` ON \`orders\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`appeal_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`appeal_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD UNIQUE INDEX \`IDX_f0b696b5d7c28733b2917bfb25\` (\`appeal_id\`)`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`payment_method_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`payment_method_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`cancel_by_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`cancel_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_e88e5acc0b2b1fe49328df6ed0f\``);
        await queryRunner.query(`ALTER TABLE \`statistics\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`statistics\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`statistics\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`statistics\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`statistics\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`statistics\` ADD \`user_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_03deebc191bbb5b9fd4b30abffc\``);
        await queryRunner.query(`ALTER TABLE \`user_infos\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_infos\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user_infos\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`user_infos\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` DROP COLUMN \`created_by_id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` ADD \`created_by_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` DROP COLUMN \`updated_by_id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` ADD \`updated_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` DROP FOREIGN KEY \`FK_76de091ca3bc0d093cd648a0570\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` DROP FOREIGN KEY \`FK_e73f283b2e2b842b231ede5e4af\``);
        await queryRunner.query(`ALTER TABLE \`notification_users\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`notification_users\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`notification_users\` ADD \`user_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` DROP COLUMN \`notification_id\``);
        await queryRunner.query(`ALTER TABLE \`notification_users\` ADD \`notification_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_4cd42f51b1f3ec6d3622bb77e6f\``);
        await queryRunner.query(`ALTER TABLE \`appeals\` DROP FOREIGN KEY \`FK_63efba62dab55e4d91f42fcbaca\``);
        await queryRunner.query(`ALTER TABLE \`appeals\` DROP FOREIGN KEY \`FK_c94cf2183ecf06b5909ecd339e1\``);
        await queryRunner.query(`ALTER TABLE \`user_devices\` DROP FOREIGN KEY \`FK_28bd79e1b3f7c1168f0904ce241\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`merchant_manager_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`merchant_manager_id\`  varchar(36) NULL`);
        await queryRunner.query(`DROP INDEX \`REL_e88e5acc0b2b1fe49328df6ed0\` ON \`users\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`statistic_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`statistic_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_e88e5acc0b2b1fe49328df6ed0\` (\`statistic_id\`)`);
        await queryRunner.query(`DROP INDEX \`REL_03deebc191bbb5b9fd4b30abff\` ON \`users\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`user_info_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`user_info_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_03deebc191bbb5b9fd4b30abff\` (\`user_info_id\`)`);
        await queryRunner.query(`ALTER TABLE \`appeals\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`appeals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`appeals\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`appeals\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`appeals\` DROP COLUMN \`winner_id\``);
        await queryRunner.query(`ALTER TABLE \`appeals\` ADD \`winner_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`appeals\` DROP COLUMN \`admin_id\``);
        await queryRunner.query(`ALTER TABLE \`appeals\` ADD \`admin_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` DROP COLUMN \`created_by_id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` ADD \`created_by_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` DROP COLUMN \`updated_by_id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` ADD \`updated_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`user_devices\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`user_devices\` ADD \`user_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`volume\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`volume\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`volume\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`volume\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`volume\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`volume\` ADD \`user_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_f0b696b5d7c28733b2917bfb25\` ON \`orders\` (\`appeal_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_03deebc191bbb5b9fd4b30abff\` ON \`users\` (\`user_info_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_e88e5acc0b2b1fe49328df6ed0\` ON \`users\` (\`statistic_id\`)`);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` ADD CONSTRAINT \`FK_1b1d3bc7dee89240f32a52ac1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` ADD CONSTRAINT \`FK_3f2c5059700f1b5aac63578f1a8\` FOREIGN KEY (\`payment_method_id\`) REFERENCES \`payment_methods\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD CONSTRAINT \`FK_717ca4859d98ff25cb6b2a1e849\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD CONSTRAINT \`FK_3dd742723f71ed49d0d4d7220bf\` FOREIGN KEY (\`asset_id\`) REFERENCES \`assets\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD CONSTRAINT \`FK_b88299cbbc4574c73b50c5d27f0\` FOREIGN KEY (\`fiat_id\`) REFERENCES \`fiats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD CONSTRAINT \`FK_ffe1b182ad69c344e48536ffd5c\` FOREIGN KEY (\`payment_method_id\`) REFERENCES \`payment_methods\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2474866c8f8e9196ff227a7cbbd\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_316f906335ce15e2848af3dd53a\` FOREIGN KEY (\`supporter_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_055606f75e7ed988a209b0cc22c\` FOREIGN KEY (\`asset_id\`) REFERENCES \`assets\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2465b00898e757903f012d835cd\` FOREIGN KEY (\`fiat_id\`) REFERENCES \`fiats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_4431880582fab347b6290ee72b2\` FOREIGN KEY (\`post_id\`) REFERENCES \`posts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_f0b696b5d7c28733b2917bfb251\` FOREIGN KEY (\`appeal_id\`) REFERENCES \`appeals\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_7819f136440d4ae83b20f0267a9\` FOREIGN KEY (\`payment_method_id\`) REFERENCES \`payment_methods\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_10d3b9250270115115b3d899d1f\` FOREIGN KEY (\`cancel_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` ADD CONSTRAINT \`FK_e73f283b2e2b842b231ede5e4af\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` ADD CONSTRAINT \`FK_76de091ca3bc0d093cd648a0570\` FOREIGN KEY (\`notification_id\`) REFERENCES \`notifications\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_4cd42f51b1f3ec6d3622bb77e6f\` FOREIGN KEY (\`merchant_manager_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_0508428800471716ac1b165df29\` FOREIGN KEY (\`merchant_level\`) REFERENCES \`master_data_levels\`(\`merchant_level\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_03deebc191bbb5b9fd4b30abffc\` FOREIGN KEY (\`user_info_id\`) REFERENCES \`user_infos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_e88e5acc0b2b1fe49328df6ed0f\` FOREIGN KEY (\`statistic_id\`) REFERENCES \`statistics\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`appeals\` ADD CONSTRAINT \`FK_c94cf2183ecf06b5909ecd339e1\` FOREIGN KEY (\`winner_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`appeals\` ADD CONSTRAINT \`FK_63efba62dab55e4d91f42fcbaca\` FOREIGN KEY (\`admin_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` ADD CONSTRAINT \`FK_28bd79e1b3f7c1168f0904ce241\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_devices\` DROP FOREIGN KEY \`FK_28bd79e1b3f7c1168f0904ce241\``);
        await queryRunner.query(`ALTER TABLE \`appeals\` DROP FOREIGN KEY \`FK_63efba62dab55e4d91f42fcbaca\``);
        await queryRunner.query(`ALTER TABLE \`appeals\` DROP FOREIGN KEY \`FK_c94cf2183ecf06b5909ecd339e1\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_e88e5acc0b2b1fe49328df6ed0f\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_03deebc191bbb5b9fd4b30abffc\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_0508428800471716ac1b165df29\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_4cd42f51b1f3ec6d3622bb77e6f\``);
        await queryRunner.query(`ALTER TABLE \`notification_users\` DROP FOREIGN KEY \`FK_76de091ca3bc0d093cd648a0570\``);
        await queryRunner.query(`ALTER TABLE \`notification_users\` DROP FOREIGN KEY \`FK_e73f283b2e2b842b231ede5e4af\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_10d3b9250270115115b3d899d1f\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_7819f136440d4ae83b20f0267a9\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_f0b696b5d7c28733b2917bfb251\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_4431880582fab347b6290ee72b2\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2465b00898e757903f012d835cd\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_055606f75e7ed988a209b0cc22c\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_316f906335ce15e2848af3dd53a\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2474866c8f8e9196ff227a7cbbd\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP FOREIGN KEY \`FK_ffe1b182ad69c344e48536ffd5c\``);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP FOREIGN KEY \`FK_b88299cbbc4574c73b50c5d27f0\``);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP FOREIGN KEY \`FK_3dd742723f71ed49d0d4d7220bf\``);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP FOREIGN KEY \`FK_717ca4859d98ff25cb6b2a1e849\``);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` DROP FOREIGN KEY \`FK_3f2c5059700f1b5aac63578f1a8\``);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` DROP FOREIGN KEY \`FK_1b1d3bc7dee89240f32a52ac1f1\``);
        await queryRunner.query(`DROP INDEX \`REL_e88e5acc0b2b1fe49328df6ed0\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`REL_03deebc191bbb5b9fd4b30abff\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`REL_f0b696b5d7c28733b2917bfb25\` ON \`orders\``);
        await queryRunner.query(`ALTER TABLE \`volume\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`volume\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`volume\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`volume\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`volume\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`volume\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`user_devices\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`user_devices\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` DROP COLUMN \`updated_by_id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` ADD \`updated_by_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` DROP COLUMN \`created_by_id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` ADD \`created_by_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`master_data_common\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`appeals\` DROP COLUMN \`admin_id\``);
        await queryRunner.query(`ALTER TABLE \`appeals\` ADD \`admin_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`appeals\` DROP COLUMN \`winner_id\``);
        await queryRunner.query(`ALTER TABLE \`appeals\` ADD \`winner_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`appeals\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`appeals\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`appeals\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`appeals\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_03deebc191bbb5b9fd4b30abff\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`user_info_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`user_info_id\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_03deebc191bbb5b9fd4b30abff\` ON \`users\` (\`user_info_id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_e88e5acc0b2b1fe49328df6ed0\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`statistic_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`statistic_id\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_e88e5acc0b2b1fe49328df6ed0\` ON \`users\` (\`statistic_id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`merchant_manager_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`merchant_manager_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` ADD CONSTRAINT \`FK_28bd79e1b3f7c1168f0904ce241\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`appeals\` ADD CONSTRAINT \`FK_c94cf2183ecf06b5909ecd339e1\` FOREIGN KEY (\`winner_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`appeals\` ADD CONSTRAINT \`FK_63efba62dab55e4d91f42fcbaca\` FOREIGN KEY (\`admin_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_4cd42f51b1f3ec6d3622bb77e6f\` FOREIGN KEY (\`merchant_manager_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` DROP COLUMN \`notification_id\``);
        await queryRunner.query(`ALTER TABLE \`notification_users\` ADD \`notification_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`notification_users\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`notification_users\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` ADD CONSTRAINT \`FK_e73f283b2e2b842b231ede5e4af\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`notification_users\` ADD CONSTRAINT \`FK_76de091ca3bc0d093cd648a0570\` FOREIGN KEY (\`notification_id\`) REFERENCES \`notifications\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` DROP COLUMN \`updated_by_id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` ADD \`updated_by_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` DROP COLUMN \`created_by_id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` ADD \`created_by_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`master_data_levels\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user_infos\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`user_infos\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user_infos\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`user_infos\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_03deebc191bbb5b9fd4b30abffc\` FOREIGN KEY (\`user_info_id\`) REFERENCES \`user_infos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`statistics\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`statistics\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`statistics\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`statistics\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`statistics\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`statistics\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_e88e5acc0b2b1fe49328df6ed0f\` FOREIGN KEY (\`statistic_id\`) REFERENCES \`statistics\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`cancel_by_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`cancel_by_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`payment_method_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`payment_method_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP INDEX \`IDX_f0b696b5d7c28733b2917bfb25\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`appeal_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`appeal_id\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_f0b696b5d7c28733b2917bfb25\` ON \`orders\` (\`appeal_id\`)`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`post_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`post_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`fiat_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`fiat_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`asset_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`asset_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`supporter_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`supporter_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`merchant_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`merchant_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`id\` bigint NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`id\` \`id\` bigint NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_10d3b9250270115115b3d899d1f\` FOREIGN KEY (\`cancel_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_f0b696b5d7c28733b2917bfb251\` FOREIGN KEY (\`appeal_id\`) REFERENCES \`appeals\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_316f906335ce15e2848af3dd53a\` FOREIGN KEY (\`supporter_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2474866c8f8e9196ff227a7cbbd\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP COLUMN \`payment_method_id\``);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD \`payment_method_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP COLUMN \`fiat_id\``);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD \`fiat_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP COLUMN \`asset_id\``);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD \`asset_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP COLUMN \`merchant_id\``);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD \`merchant_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`posts\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD CONSTRAINT \`FK_717ca4859d98ff25cb6b2a1e849\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_4431880582fab347b6290ee72b2\` FOREIGN KEY (\`post_id\`) REFERENCES \`posts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_7819f136440d4ae83b20f0267a9\` FOREIGN KEY (\`payment_method_id\`) REFERENCES \`payment_methods\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD CONSTRAINT \`FK_ffe1b182ad69c344e48536ffd5c\` FOREIGN KEY (\`payment_method_id\`) REFERENCES \`payment_methods\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` DROP COLUMN \`payment_method_id\``);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` ADD \`payment_method_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`payment_method_fields\` ADD CONSTRAINT \`FK_3f2c5059700f1b5aac63578f1a8\` FOREIGN KEY (\`payment_method_id\`) REFERENCES \`payment_methods\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`fiats\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`fiats\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`fiats\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`fiats\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2465b00898e757903f012d835cd\` FOREIGN KEY (\`fiat_id\`) REFERENCES \`fiats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD CONSTRAINT \`FK_b88299cbbc4574c73b50c5d27f0\` FOREIGN KEY (\`fiat_id\`) REFERENCES \`fiats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` DROP COLUMN \`order_id\``);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` ADD \`order_id\` bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` ADD \`id\` bigint NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` CHANGE \`id\` \`id\` bigint NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`crypto_transactions\` ADD CONSTRAINT \`FK_1b1d3bc7dee89240f32a52ac1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assets\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`assets\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`assets\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`assets\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_055606f75e7ed988a209b0cc22c\` FOREIGN KEY (\`asset_id\`) REFERENCES \`assets\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD CONSTRAINT \`FK_3dd742723f71ed49d0d4d7220bf\` FOREIGN KEY (\`asset_id\`) REFERENCES \`assets\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_771ab23b45783e766836b2b44af\` FOREIGN KEY (\`merchant_level\`) REFERENCES \`master_data_levels\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
