export enum UserReportType {
  ORDER_HISTORIES = 'ORDER_HISTORIES',
  ASSET = 'ASSET',
  TRADE_TYPE_DIFFERENCE = 'TRADE_TYPE_DIFFERENCE',
}

export enum MerchantManagerReportType {
  ORDER_HISTORIES = 'ORDER_HISTORIES',
  POST_HISTORIES = 'POST_HISTORIES',
  ASSET = 'ASSET',
  TRADE_TYPE_DIFFERENCE = 'TRADE_TYPE_DIFFERENCE',
  STAFF_STATISTIC = 'STAFF_STATISTIC',
}

export enum MerchantOperatorReportType {
  ORDER_HISTORIES = 'ORDER_HISTORIES',
  POST_HISTORIES = 'POST_HISTORIES',
  ASSET = 'ASSET',
  TRADE_TYPE_DIFFERENCE = 'TRADE_TYPE_DIFFERENCE',
}
